export const APP_MENU = {
  dashboard: {
    module: 'Dashboard',
    overview: 'Overview',
    scheduleDoor: 'ScheduleDoor',
    summaryBooking: 'SummaryBooking',
    slottimeBooking: 'SlottimeBooking',
    dockdoorControl: 'DockdoorControl',
  },
  master: {
    module: 'Master',
    warehouse: 'Warehouse',
    operationType: 'OperationType',
    door: 'Door',
    warehousecapacity: 'WarehouseCapacity',
    warehouseOperationCapacity: 'WarehouseOperationCapacity',
    supplierGroup: 'SupplierGroup',
    supplier: 'Supplier',
    estimateTime: 'EstimateTime',
    yard: 'Yard',
  },
  booking: {
    module: 'Booking',
    createBooking: 'CreateBooking',
    createBookingExcel: 'CreateBookingExcel',
    bookingHeader: 'BookingHeader',
    createBookingNopo: 'CreateBookingNopo',
    checkPo: 'CheckPo',
    poMonitor: 'PoMonitor',
    capMonitor: 'CapMonitor',
  },
  precheckin: {
    module: 'PreCheckIn',
    preCheckInExcel: 'PreCheckInExcel',
    preCheckInCompleted: 'PreCheckInCompleted',
  },
  checkinout: {
    module: 'CheckInOut',
    guardCheckIn: 'GuardCheckIn',
    guardCheckOut: 'GuardCheckOut',
  },
  queuemanage: {
    module: 'QueueManage',
    documentCheckIn: 'DocumentCheckIn',
    manageQueue: 'ManageQueue',
    documentConfirmation: 'DocumentConfirmation',
    guardCreateBooking: 'GuardCreateBooking',
  },
  opsmanage: {
    module: 'OpsManage',
    dockdoorList: 'DockDoorList',
  },
  yardmanagement: {
    module: 'Yard',
    yardBooking: 'Yard Booking',
    createBookingExcel: 'CreateBookingExcel',
    bookingHeader: 'BookingHeader',
    createBookingNopo: 'CreateBookingNopo',
    checkPo: 'CheckPo',
  },
  report: {
    module: 'Report',
    truckStatus: 'TruckStatus',
    transactionTrack: 'TransactionTrack',
  },
  yardmaster: {
    module: 'YardMaster',
    yard: 'Yard',
    trailer: 'Trailer',
    shunt: 'Shunt',
  },
  transfer: {
    module: 'Transfer',
    yardMonitor: 'YardMonitor',
    trailerMonitor: 'TrailerMonitor',
    transferTrailerEmpty: 'TransferTrailerEmpty',
    transferTrailerFull: 'TransferTrailerFull',
    transferList: 'TransferList',
    transferProcess: 'TransferProcess',
    transferReport: 'TransferReport',
  },
  account: {
    module: 'Account',
    userProfile: 'UserProfile',
    userMaster: 'UserMaster',
    supplierContact: 'SupplierContact',
    resetPassword: 'ResetPassword',
  },
};
